# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Business\SaleManagement\Sales-Management-PyQt5-MySQL\UI\account.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 596)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolTip("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 871, 541))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setMidLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageEntry = QtWidgets.QWidget()
        self.pageEntry.setObjectName("pageEntry")
        self.ButtonSubmit = QtWidgets.QPushButton(self.pageEntry)
        self.ButtonSubmit.setGeometry(QtCore.QRect(410, 500, 75, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonSubmit.sizePolicy().hasHeightForWidth())
        self.ButtonSubmit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.ButtonSubmit.setFont(font)
        self.ButtonSubmit.setObjectName("ButtonSubmit")
        self.groupBoxCustomerInfo = QtWidgets.QGroupBox(self.pageEntry)
        self.groupBoxCustomerInfo.setGeometry(QtCore.QRect(30, 20, 420, 471))
        self.groupBoxCustomerInfo.setTitle("")
        self.groupBoxCustomerInfo.setObjectName("groupBoxCustomerInfo")
        self.labelPhone = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        self.labelPhone.setGeometry(QtCore.QRect(9, 430, 53, 22))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.labelPhone.setFont(font)
        self.labelPhone.setToolTip("")
        self.labelPhone.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelPhone.setObjectName("labelPhone")
        self.labelName = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        self.labelName.setGeometry(QtCore.QRect(9, 50, 47, 22))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.labelName.setFont(font)
        self.labelName.setToolTip("")
        self.labelName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelName.setObjectName("labelName")
        self.comboCity = QtWidgets.QComboBox(self.groupBoxCustomerInfo)
        self.comboCity.setGeometry(QtCore.QRect(95, 201, 250, 24))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.comboCity.setFont(font)
        self.comboCity.setEditable(True)
        self.comboCity.setObjectName("comboCity")
        self.labelAddress = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        self.labelAddress.setGeometry(QtCore.QRect(10, 240, 66, 22))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.labelAddress.setFont(font)
        self.labelAddress.setToolTip("")
        self.labelAddress.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelAddress.setObjectName("labelAddress")
        self.labelZip = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        self.labelZip.setGeometry(QtCore.QRect(9, 380, 23, 22))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.labelZip.setFont(font)
        self.labelZip.setToolTip("")
        self.labelZip.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelZip.setObjectName("labelZip")
        self.textCustomerID = QtWidgets.QLineEdit(self.groupBoxCustomerInfo)
        self.textCustomerID.setGeometry(QtCore.QRect(95, 103, 250, 27))
        self.textCustomerID.setMaximumSize(QtCore.QSize(446, 16777215))
        font = QtGui.QFont()
        font.setFamily("serif")
        font.setPointSize(14)
        self.textCustomerID.setFont(font)
        self.textCustomerID.setObjectName("textCustomerID")
        self.labelCity = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        self.labelCity.setGeometry(QtCore.QRect(9, 201, 31, 22))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.labelCity.setFont(font)
        self.labelCity.setToolTip("")
        self.labelCity.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelCity.setObjectName("labelCity")
        self.comboProvince = QtWidgets.QComboBox(self.groupBoxCustomerInfo)
        self.comboProvince.setGeometry(QtCore.QRect(95, 155, 250, 24))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.comboProvince.setFont(font)
        self.comboProvince.setEditable(False)
        self.comboProvince.setObjectName("comboProvince")
        self.labelProvince = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        self.labelProvince.setGeometry(QtCore.QRect(9, 156, 80, 22))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.labelProvince.setFont(font)
        self.labelProvince.setToolTip("")
        self.labelProvince.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProvince.setObjectName("labelProvince")
        self.textZip = QtWidgets.QLineEdit(self.groupBoxCustomerInfo)
        self.textZip.setGeometry(QtCore.QRect(95, 380, 250, 27))
        font = QtGui.QFont()
        font.setFamily("serif")
        font.setPointSize(14)
        self.textZip.setFont(font)
        self.textZip.setObjectName("textZip")
        self.textPhone = QtWidgets.QLineEdit(self.groupBoxCustomerInfo)
        self.textPhone.setGeometry(QtCore.QRect(95, 430, 250, 27))
        font = QtGui.QFont()
        font.setFamily("serif")
        font.setPointSize(14)
        self.textPhone.setFont(font)
        self.textPhone.setObjectName("textPhone")
        self.labelCustomerID = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        self.labelCustomerID.setGeometry(QtCore.QRect(9, 103, 18, 22))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.labelCustomerID.setFont(font)
        self.labelCustomerID.setToolTip("")
        self.labelCustomerID.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelCustomerID.setObjectName("labelCustomerID")
        self.textName = QtWidgets.QLineEdit(self.groupBoxCustomerInfo)
        self.textName.setGeometry(QtCore.QRect(95, 50, 250, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textName.sizePolicy().hasHeightForWidth())
        self.textName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("serif")
        font.setPointSize(14)
        self.textName.setFont(font)
        self.textName.setStyleSheet("")
        self.textName.setObjectName("textName")
        self.textAddress = QtWidgets.QTextEdit(self.groupBoxCustomerInfo)
        self.textAddress.setGeometry(QtCore.QRect(95, 246, 250, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textAddress.sizePolicy().hasHeightForWidth())
        self.textAddress.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("serif")
        self.textAddress.setFont(font)
        self.textAddress.setObjectName("textAddress")
        self.labelCustomerInfo = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        self.labelCustomerInfo.setGeometry(QtCore.QRect(140, 9, 130, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCustomerInfo.sizePolicy().hasHeightForWidth())
        self.labelCustomerInfo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.labelCustomerInfo.setFont(font)
        self.labelCustomerInfo.setToolTip("")
        self.labelCustomerInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCustomerInfo.setObjectName("labelCustomerInfo")
        self.groupBoxOrderInfo = QtWidgets.QGroupBox(self.pageEntry)
        self.groupBoxOrderInfo.setGeometry(QtCore.QRect(460, 20, 381, 471))
        self.groupBoxOrderInfo.setStyleSheet("")
        self.groupBoxOrderInfo.setTitle("")
        self.groupBoxOrderInfo.setObjectName("groupBoxOrderInfo")
        self.labelOrderInfo = QtWidgets.QLabel(self.groupBoxOrderInfo)
        self.labelOrderInfo.setGeometry(QtCore.QRect(100, 10, 211, 23))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.labelOrderInfo.setFont(font)
        self.labelOrderInfo.setToolTip("")
        self.labelOrderInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOrderInfo.setObjectName("labelOrderInfo")
        self.labelOrderDate = QtWidgets.QLabel(self.groupBoxOrderInfo)
        self.labelOrderDate.setGeometry(QtCore.QRect(30, 50, 46, 23))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.labelOrderDate.setFont(font)
        self.labelOrderDate.setToolTip("")
        self.labelOrderDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOrderDate.setObjectName("labelOrderDate")
        self.textDate = QtWidgets.QLineEdit(self.groupBoxOrderInfo)
        self.textDate.setGeometry(QtCore.QRect(130, 50, 250, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textDate.sizePolicy().hasHeightForWidth())
        self.textDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("serif")
        font.setPointSize(14)
        self.textDate.setFont(font)
        self.textDate.setObjectName("textDate")
        self.labelItem = QtWidgets.QLabel(self.groupBoxOrderInfo)
        self.labelItem.setGeometry(QtCore.QRect(30, 110, 46, 23))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.labelItem.setFont(font)
        self.labelItem.setToolTip("")
        self.labelItem.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelItem.setObjectName("labelItem")
        self.labelQuantity = QtWidgets.QLabel(self.groupBoxOrderInfo)
        self.labelQuantity.setGeometry(QtCore.QRect(30, 170, 71, 23))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.labelQuantity.setFont(font)
        self.labelQuantity.setToolTip("")
        self.labelQuantity.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelQuantity.setObjectName("labelQuantity")
        self.comboQuantity = QtWidgets.QComboBox(self.groupBoxOrderInfo)
        self.comboQuantity.setGeometry(QtCore.QRect(130, 170, 250, 28))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.comboQuantity.setFont(font)
        self.comboQuantity.setEditable(True)
        self.comboQuantity.setObjectName("comboQuantity")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboItem = QtWidgets.QComboBox(self.groupBoxOrderInfo)
        self.comboItem.setGeometry(QtCore.QRect(130, 110, 250, 28))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.comboItem.setFont(font)
        self.comboItem.setEditable(True)
        self.comboItem.setObjectName("comboItem")
        self.comboItem.addItem("")
        self.comboItem.addItem("")
        self.comboItem.addItem("")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBoxOrderInfo)
        self.calendarWidget.setGeometry(QtCore.QRect(130, 80, 256, 183))
        self.calendarWidget.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.stackedWidget.addWidget(self.pageEntry)
        self.pageResult = QtWidgets.QWidget()
        self.pageResult.setObjectName("pageResult")
        self.comboQuery = QtWidgets.QComboBox(self.pageResult)
        self.comboQuery.setGeometry(QtCore.QRect(140, 30, 121, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboQuery.sizePolicy().hasHeightForWidth())
        self.comboQuery.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.comboQuery.setFont(font)
        self.comboQuery.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboQuery.setObjectName("comboQuery")
        self.comboQuery.addItem("")
        self.comboQuery.addItem("")
        self.comboQuery.addItem("")
        self.comboQuery.addItem("")
        self.comboQuery.addItem("")
        self.comboQuery.addItem("")
        self.ButtonQuery = QtWidgets.QPushButton(self.pageResult)
        self.ButtonQuery.setGeometry(QtCore.QRect(510, 30, 75, 28))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.ButtonQuery.setFont(font)
        self.ButtonQuery.setObjectName("ButtonQuery")
        self.labelKeyWord = QtWidgets.QLabel(self.pageResult)
        self.labelKeyWord.setGeometry(QtCore.QRect(50, 30, 71, 20))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.labelKeyWord.setFont(font)
        self.labelKeyWord.setObjectName("labelKeyWord")
        self.label = QtWidgets.QLabel(self.pageResult)
        self.label.setGeometry(QtCore.QRect(372, 9, 88, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("century gothic")
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.TextKeyWord = QtWidgets.QLineEdit(self.pageResult)
        self.TextKeyWord.setGeometry(QtCore.QRect(280, 30, 221, 27))
        font = QtGui.QFont()
        font.setFamily("serif")
        font.setPointSize(14)
        self.TextKeyWord.setFont(font)
        self.TextKeyWord.setObjectName("TextKeyWord")
        self.textResult = QtWidgets.QTextEdit(self.pageResult)
        self.textResult.setGeometry(QtCore.QRect(20, 69, 831, 151))
        self.textResult.setObjectName("textResult")
        self.tableResult = QtWidgets.QTableView(self.pageResult)
        self.tableResult.setGeometry(QtCore.QRect(20, 230, 831, 311))
        self.tableResult.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableResult.setObjectName("tableResult")
        self.stackedWidget.addWidget(self.pageResult)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 21))
        self.menubar.setObjectName("menubar")
        self.menuNEW = QtWidgets.QMenu(self.menubar)
        self.menuNEW.setGeometry(QtCore.QRect(1581, 123, 135, 72))
        self.menuNEW.setObjectName("menuNEW")
        self.menuQUERY = QtWidgets.QMenu(self.menubar)
        self.menuQUERY.setGeometry(QtCore.QRect(1623, 123, 135, 72))
        self.menuQUERY.setObjectName("menuQUERY")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewRecord = QtWidgets.QAction(MainWindow)
        self.actionNewRecord.setObjectName("actionNewRecord")
        self.actionQuery = QtWidgets.QAction(MainWindow)
        self.actionQuery.setObjectName("actionQuery")
        self.actionBy_Customer_ID = QtWidgets.QAction(MainWindow)
        self.actionBy_Customer_ID.setObjectName("actionBy_Customer_ID")
        self.actionBy_Order_ID = QtWidgets.QAction(MainWindow)
        self.actionBy_Order_ID.setObjectName("actionBy_Order_ID")
        self.menuNEW.addAction(self.actionNewRecord)
        self.menuQUERY.addAction(self.actionQuery)
        self.menubar.addAction(self.menuNEW.menuAction())
        self.menubar.addAction(self.menuQUERY.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sales Management"))
        self.ButtonSubmit.setText(_translate("MainWindow", "SUBMIT"))
        self.labelPhone.setText(_translate("MainWindow", "PHONE"))
        self.labelName.setText(_translate("MainWindow", "NAME"))
        self.comboCity.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请选择城市</p></body></html>"))
        self.labelAddress.setText(_translate("MainWindow", "ADDRESS"))
        self.labelZip.setText(_translate("MainWindow", "ZIP"))
        self.textCustomerID.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请输入身份证号码</p></body></html>"))
        self.labelCity.setText(_translate("MainWindow", "CITY"))
        self.comboProvince.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请选择省份</p></body></html>"))
        self.labelProvince.setText(_translate("MainWindow", "PROVINCE"))
        self.textZip.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请输入邮政编码</p></body></html>"))
        self.textPhone.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请输入手机号</p></body></html>"))
        self.labelCustomerID.setText(_translate("MainWindow", "ID"))
        self.textName.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请输入姓名</p></body></html>"))
        self.textAddress.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请输入地址</p></body></html>"))
        self.labelCustomerInfo.setText(_translate("MainWindow", "Customer Info"))
        self.labelOrderInfo.setText(_translate("MainWindow", "Order Info"))
        self.labelOrderDate.setText(_translate("MainWindow", "DATE"))
        self.textDate.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请输入姓名</p></body></html>"))
        self.labelItem.setText(_translate("MainWindow", "ITEM"))
        self.labelQuantity.setText(_translate("MainWindow", "QUANTITY"))
        self.comboQuantity.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请选择产品</p></body></html>"))
        self.comboQuantity.setItemText(0, _translate("MainWindow", "1"))
        self.comboQuantity.setItemText(1, _translate("MainWindow", "2"))
        self.comboQuantity.setItemText(2, _translate("MainWindow", "3"))
        self.comboQuantity.setItemText(3, _translate("MainWindow", "4"))
        self.comboQuantity.setItemText(4, _translate("MainWindow", "5"))
        self.comboQuantity.setItemText(5, _translate("MainWindow", "6"))
        self.comboQuantity.setItemText(6, _translate("MainWindow", "7"))
        self.comboQuantity.setItemText(7, _translate("MainWindow", "8"))
        self.comboQuantity.setItemText(8, _translate("MainWindow", "9"))
        self.comboQuantity.setItemText(9, _translate("MainWindow", "10"))
        self.comboQuantity.setItemText(10, _translate("MainWindow", "11"))
        self.comboQuantity.setItemText(11, _translate("MainWindow", "12"))
        self.comboQuantity.setItemText(12, _translate("MainWindow", "13"))
        self.comboQuantity.setItemText(13, _translate("MainWindow", "14"))
        self.comboQuantity.setItemText(14, _translate("MainWindow", "15"))
        self.comboQuantity.setItemText(15, _translate("MainWindow", "16"))
        self.comboQuantity.setItemText(16, _translate("MainWindow", "17"))
        self.comboQuantity.setItemText(17, _translate("MainWindow", "18"))
        self.comboQuantity.setItemText(18, _translate("MainWindow", "19"))
        self.comboQuantity.setItemText(19, _translate("MainWindow", "20"))
        self.comboQuantity.setItemText(20, _translate("MainWindow", "21"))
        self.comboQuantity.setItemText(21, _translate("MainWindow", "22"))
        self.comboQuantity.setItemText(22, _translate("MainWindow", "23"))
        self.comboQuantity.setItemText(23, _translate("MainWindow", "24"))
        self.comboItem.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请选择产品</p></body></html>"))
        self.comboItem.setItemText(0, _translate("MainWindow", "1"))
        self.comboItem.setItemText(1, _translate("MainWindow", "2"))
        self.comboItem.setItemText(2, _translate("MainWindow", "3"))
        self.comboQuery.setItemText(0, _translate("MainWindow", "name"))
        self.comboQuery.setItemText(1, _translate("MainWindow", "personID"))
        self.comboQuery.setItemText(2, _translate("MainWindow", "province"))
        self.comboQuery.setItemText(3, _translate("MainWindow", "city"))
        self.comboQuery.setItemText(4, _translate("MainWindow", "zip"))
        self.comboQuery.setItemText(5, _translate("MainWindow", "phone"))
        self.ButtonQuery.setText(_translate("MainWindow", "Go"))
        self.labelKeyWord.setText(_translate("MainWindow", "Key Word"))
        self.label.setText(_translate("MainWindow", "Sales Details"))
        self.menuNEW.setTitle(_translate("MainWindow", "NEW"))
        self.menuQUERY.setTitle(_translate("MainWindow", "QUERY"))
        self.actionNewRecord.setText(_translate("MainWindow", "New Record"))
        self.actionQuery.setText(_translate("MainWindow", "Query"))
        self.actionBy_Customer_ID.setText(_translate("MainWindow", "By Customer ID"))
        self.actionBy_Order_ID.setText(_translate("MainWindow", "By Order ID"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
