# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Business\UI\account.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 663)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolTip("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setMidLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageEntry = QtWidgets.QWidget()
        self.pageEntry.setObjectName("pageEntry")
        self.gridLayout = QtWidgets.QGridLayout(self.pageEntry)
        self.gridLayout.setObjectName("gridLayout")
        self.ButtonSubmit = QtWidgets.QPushButton(self.pageEntry)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonSubmit.sizePolicy().hasHeightForWidth())
        self.ButtonSubmit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(14)
        self.ButtonSubmit.setFont(font)
        self.ButtonSubmit.setObjectName("ButtonSubmit")
        self.gridLayout.addWidget(self.ButtonSubmit, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.groupBoxCustomerInfo = QtWidgets.QGroupBox(self.pageEntry)
        self.groupBoxCustomerInfo.setTitle("")
        self.groupBoxCustomerInfo.setObjectName("groupBoxCustomerInfo")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxCustomerInfo)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelPhone = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.labelPhone.setFont(font)
        self.labelPhone.setToolTip("")
        self.labelPhone.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelPhone.setObjectName("labelPhone")
        self.gridLayout_2.addWidget(self.labelPhone, 19, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 5, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 11, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 2, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 13, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 9, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 18, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 0, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 20, 0, 1, 1)
        self.labelName = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.labelName.setFont(font)
        self.labelName.setToolTip("")
        self.labelName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelName.setObjectName("labelName")
        self.gridLayout_2.addWidget(self.labelName, 4, 0, 1, 1)
        self.comboCity = QtWidgets.QComboBox(self.groupBoxCustomerInfo)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.comboCity.setFont(font)
        self.comboCity.setEditable(True)
        self.comboCity.setObjectName("comboCity")
        self.gridLayout_2.addWidget(self.comboCity, 12, 2, 1, 1)
        self.labelAddress = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.labelAddress.setFont(font)
        self.labelAddress.setToolTip("")
        self.labelAddress.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelAddress.setObjectName("labelAddress")
        self.gridLayout_2.addWidget(self.labelAddress, 15, 0, 1, 1)
        self.labelZip = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.labelZip.setFont(font)
        self.labelZip.setToolTip("")
        self.labelZip.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelZip.setObjectName("labelZip")
        self.gridLayout_2.addWidget(self.labelZip, 17, 0, 1, 2)
        self.textCustomerID = QtWidgets.QLineEdit(self.groupBoxCustomerInfo)
        self.textCustomerID.setMaximumSize(QtCore.QSize(446, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.textCustomerID.setFont(font)
        self.textCustomerID.setObjectName("textCustomerID")
        self.gridLayout_2.addWidget(self.textCustomerID, 8, 2, 1, 1)
        self.labelCity = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.labelCity.setFont(font)
        self.labelCity.setToolTip("")
        self.labelCity.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelCity.setObjectName("labelCity")
        self.gridLayout_2.addWidget(self.labelCity, 12, 0, 1, 1)
        self.comboProvince = QtWidgets.QComboBox(self.groupBoxCustomerInfo)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.comboProvince.setFont(font)
        self.comboProvince.setEditable(True)
        self.comboProvince.setObjectName("comboProvince")
        self.gridLayout_2.addWidget(self.comboProvince, 10, 2, 1, 1)
        self.labelProvince = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.labelProvince.setFont(font)
        self.labelProvince.setToolTip("")
        self.labelProvince.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProvince.setObjectName("labelProvince")
        self.gridLayout_2.addWidget(self.labelProvince, 10, 0, 1, 2)
        self.textZip = QtWidgets.QLineEdit(self.groupBoxCustomerInfo)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.textZip.setFont(font)
        self.textZip.setObjectName("textZip")
        self.gridLayout_2.addWidget(self.textZip, 17, 2, 1, 1)
        self.textPhone = QtWidgets.QLineEdit(self.groupBoxCustomerInfo)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.textPhone.setFont(font)
        self.textPhone.setObjectName("textPhone")
        self.gridLayout_2.addWidget(self.textPhone, 19, 2, 1, 1)
        self.labelCustomerID = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.labelCustomerID.setFont(font)
        self.labelCustomerID.setToolTip("")
        self.labelCustomerID.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelCustomerID.setObjectName("labelCustomerID")
        self.gridLayout_2.addWidget(self.labelCustomerID, 8, 0, 1, 1)
        self.textName = QtWidgets.QLineEdit(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textName.sizePolicy().hasHeightForWidth())
        self.textName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.textName.setFont(font)
        self.textName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textName.setObjectName("textName")
        self.gridLayout_2.addWidget(self.textName, 4, 2, 1, 1)
        self.textAddress = QtWidgets.QTextEdit(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textAddress.sizePolicy().hasHeightForWidth())
        self.textAddress.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.textAddress.setFont(font)
        self.textAddress.setObjectName("textAddress")
        self.gridLayout_2.addWidget(self.textAddress, 15, 2, 1, 1)
        self.labelCustomerInfo = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCustomerInfo.sizePolicy().hasHeightForWidth())
        self.labelCustomerInfo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.labelCustomerInfo.setFont(font)
        self.labelCustomerInfo.setToolTip("")
        self.labelCustomerInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCustomerInfo.setObjectName("labelCustomerInfo")
        self.gridLayout_2.addWidget(self.labelCustomerInfo, 1, 0, 1, 3)
        self.gridLayout.addWidget(self.groupBoxCustomerInfo, 0, 0, 1, 1)
        self.groupBoxOrderInfo = QtWidgets.QGroupBox(self.pageEntry)
        self.groupBoxOrderInfo.setTitle("")
        self.groupBoxOrderInfo.setObjectName("groupBoxOrderInfo")
        self.labelOrderInfo = QtWidgets.QLabel(self.groupBoxOrderInfo)
        self.labelOrderInfo.setGeometry(QtCore.QRect(90, 30, 211, 23))
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.labelOrderInfo.setFont(font)
        self.labelOrderInfo.setToolTip("")
        self.labelOrderInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOrderInfo.setObjectName("labelOrderInfo")
        self.labelOrderDate = QtWidgets.QLabel(self.groupBoxOrderInfo)
        self.labelOrderDate.setGeometry(QtCore.QRect(40, 100, 46, 23))
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.labelOrderDate.setFont(font)
        self.labelOrderDate.setToolTip("")
        self.labelOrderDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOrderDate.setObjectName("labelOrderDate")
        self.textDate = QtWidgets.QLineEdit(self.groupBoxOrderInfo)
        self.textDate.setGeometry(QtCore.QRect(160, 100, 167, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textDate.sizePolicy().hasHeightForWidth())
        self.textDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.textDate.setFont(font)
        self.textDate.setObjectName("textDate")
        self.labelItem = QtWidgets.QLabel(self.groupBoxOrderInfo)
        self.labelItem.setGeometry(QtCore.QRect(40, 160, 46, 23))
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.labelItem.setFont(font)
        self.labelItem.setToolTip("")
        self.labelItem.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelItem.setObjectName("labelItem")
        self.labelQuantity = QtWidgets.QLabel(self.groupBoxOrderInfo)
        self.labelQuantity.setGeometry(QtCore.QRect(40, 210, 101, 23))
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.labelQuantity.setFont(font)
        self.labelQuantity.setToolTip("")
        self.labelQuantity.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelQuantity.setObjectName("labelQuantity")
        self.comboQuantity = QtWidgets.QComboBox(self.groupBoxOrderInfo)
        self.comboQuantity.setGeometry(QtCore.QRect(160, 210, 167, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.comboQuantity.setFont(font)
        self.comboQuantity.setEditable(True)
        self.comboQuantity.setObjectName("comboQuantity")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboQuantity.addItem("")
        self.comboItem = QtWidgets.QComboBox(self.groupBoxOrderInfo)
        self.comboItem.setGeometry(QtCore.QRect(160, 160, 167, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.comboItem.setFont(font)
        self.comboItem.setEditable(True)
        self.comboItem.setObjectName("comboItem")
        self.comboItem.addItem("")
        self.comboItem.addItem("")
        self.comboItem.addItem("")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBoxOrderInfo)
        self.calendarWidget.setGeometry(QtCore.QRect(160, 130, 256, 183))
        self.calendarWidget.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.groupBoxOrderInfo, 0, 1, 1, 2)
        self.stackedWidget.addWidget(self.pageEntry)
        self.pageResult = QtWidgets.QWidget()
        self.pageResult.setObjectName("pageResult")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.pageResult)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 0, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 0, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 0, 6, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem14, 0, 7, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem15, 1, 7, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem16, 0, 9, 1, 1)
        self.tableResult = QtWidgets.QTableView(self.pageResult)
        self.tableResult.setShowGrid(True)
        self.tableResult.setObjectName("tableResult")
        self.gridLayout_4.addWidget(self.tableResult, 3, 0, 1, 14)
        self.comboQuery = QtWidgets.QComboBox(self.pageResult)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboQuery.sizePolicy().hasHeightForWidth())
        self.comboQuery.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(11)
        self.comboQuery.setFont(font)
        self.comboQuery.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboQuery.setObjectName("comboQuery")
        self.comboQuery.addItem("")
        self.comboQuery.addItem("")
        self.comboQuery.addItem("")
        self.comboQuery.addItem("")
        self.comboQuery.addItem("")
        self.comboQuery.addItem("")
        self.gridLayout_4.addWidget(self.comboQuery, 1, 3, 1, 4)
        self.ButtonQuery = QtWidgets.QPushButton(self.pageResult)
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(12)
        self.ButtonQuery.setFont(font)
        self.ButtonQuery.setObjectName("ButtonQuery")
        self.gridLayout_4.addWidget(self.ButtonQuery, 1, 12, 1, 1)
        self.labelKeyWord = QtWidgets.QLabel(self.pageResult)
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(12)
        self.labelKeyWord.setFont(font)
        self.labelKeyWord.setObjectName("labelKeyWord")
        self.gridLayout_4.addWidget(self.labelKeyWord, 1, 0, 1, 2)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem17, 1, 13, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem18, 1, 11, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem19, 0, 12, 1, 2)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem20, 0, 10, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem21, 0, 3, 1, 3)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem22, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.pageResult)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 8, 1, 1)
        self.TextKeyWord = QtWidgets.QLineEdit(self.pageResult)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.TextKeyWord.setFont(font)
        self.TextKeyWord.setObjectName("TextKeyWord")
        self.gridLayout_4.addWidget(self.TextKeyWord, 1, 8, 1, 3)
        self.stackedWidget.addWidget(self.pageResult)
        self.gridLayout_3.addWidget(self.stackedWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 874, 21))
        self.menubar.setObjectName("menubar")
        self.menuNEW = QtWidgets.QMenu(self.menubar)
        self.menuNEW.setGeometry(QtCore.QRect(1581, 123, 135, 72))
        self.menuNEW.setObjectName("menuNEW")
        self.menuQUERY = QtWidgets.QMenu(self.menubar)
        self.menuQUERY.setGeometry(QtCore.QRect(1623, 123, 135, 72))
        self.menuQUERY.setObjectName("menuQUERY")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewRecord = QtWidgets.QAction(MainWindow)
        self.actionNewRecord.setObjectName("actionNewRecord")
        self.actionQuery = QtWidgets.QAction(MainWindow)
        self.actionQuery.setObjectName("actionQuery")
        self.actionBy_Customer_ID = QtWidgets.QAction(MainWindow)
        self.actionBy_Customer_ID.setObjectName("actionBy_Customer_ID")
        self.actionBy_Order_ID = QtWidgets.QAction(MainWindow)
        self.actionBy_Order_ID.setObjectName("actionBy_Order_ID")
        self.menuNEW.addAction(self.actionNewRecord)
        self.menuQUERY.addAction(self.actionQuery)
        self.menubar.addAction(self.menuNEW.menuAction())
        self.menubar.addAction(self.menuQUERY.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sales Management"))
        self.ButtonSubmit.setText(_translate("MainWindow", "SUBMIT"))
        self.labelPhone.setText(_translate("MainWindow", "PHONE"))
        self.labelName.setText(_translate("MainWindow", "NAME"))
        self.comboCity.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请选择城市</p></body></html>"))
        self.labelAddress.setText(_translate("MainWindow", "ADDRESS"))
        self.labelZip.setText(_translate("MainWindow", "ZIP"))
        self.textCustomerID.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请输入身份证号码</p></body></html>"))
        self.labelCity.setText(_translate("MainWindow", "CITY"))
        self.comboProvince.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请选择省份</p></body></html>"))
        self.labelProvince.setText(_translate("MainWindow", "PROVINCE"))
        self.textZip.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请输入邮政编码</p></body></html>"))
        self.textPhone.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请输入手机号</p></body></html>"))
        self.labelCustomerID.setText(_translate("MainWindow", "ID"))
        self.textName.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请输入姓名</p></body></html>"))
        self.textAddress.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请输入地址</p></body></html>"))
        self.labelCustomerInfo.setText(_translate("MainWindow", "Customer Info"))
        self.labelOrderInfo.setText(_translate("MainWindow", "Order Info"))
        self.labelOrderDate.setText(_translate("MainWindow", "DATE"))
        self.textDate.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请输入姓名</p></body></html>"))
        self.labelItem.setText(_translate("MainWindow", "ITEM"))
        self.labelQuantity.setText(_translate("MainWindow", "QUANTITY"))
        self.comboQuantity.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请选择产品</p></body></html>"))
        self.comboQuantity.setItemText(0, _translate("MainWindow", "1"))
        self.comboQuantity.setItemText(1, _translate("MainWindow", "2"))
        self.comboQuantity.setItemText(2, _translate("MainWindow", "3"))
        self.comboQuantity.setItemText(3, _translate("MainWindow", "4"))
        self.comboQuantity.setItemText(4, _translate("MainWindow", "5"))
        self.comboQuantity.setItemText(5, _translate("MainWindow", "6"))
        self.comboQuantity.setItemText(6, _translate("MainWindow", "7"))
        self.comboQuantity.setItemText(7, _translate("MainWindow", "8"))
        self.comboQuantity.setItemText(8, _translate("MainWindow", "9"))
        self.comboQuantity.setItemText(9, _translate("MainWindow", "10"))
        self.comboQuantity.setItemText(10, _translate("MainWindow", "11"))
        self.comboQuantity.setItemText(11, _translate("MainWindow", "12"))
        self.comboQuantity.setItemText(12, _translate("MainWindow", "13"))
        self.comboQuantity.setItemText(13, _translate("MainWindow", "14"))
        self.comboQuantity.setItemText(14, _translate("MainWindow", "15"))
        self.comboQuantity.setItemText(15, _translate("MainWindow", "16"))
        self.comboQuantity.setItemText(16, _translate("MainWindow", "17"))
        self.comboQuantity.setItemText(17, _translate("MainWindow", "18"))
        self.comboQuantity.setItemText(18, _translate("MainWindow", "19"))
        self.comboQuantity.setItemText(19, _translate("MainWindow", "20"))
        self.comboQuantity.setItemText(20, _translate("MainWindow", "21"))
        self.comboQuantity.setItemText(21, _translate("MainWindow", "22"))
        self.comboQuantity.setItemText(22, _translate("MainWindow", "23"))
        self.comboQuantity.setItemText(23, _translate("MainWindow", "24"))
        self.comboItem.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">请选择产品</p></body></html>"))
        self.comboItem.setItemText(0, _translate("MainWindow", "1"))
        self.comboItem.setItemText(1, _translate("MainWindow", "2"))
        self.comboItem.setItemText(2, _translate("MainWindow", "3"))
        self.comboQuery.setItemText(0, _translate("MainWindow", "name"))
        self.comboQuery.setItemText(1, _translate("MainWindow", "personID"))
        self.comboQuery.setItemText(2, _translate("MainWindow", "province"))
        self.comboQuery.setItemText(3, _translate("MainWindow", "city"))
        self.comboQuery.setItemText(4, _translate("MainWindow", "zip"))
        self.comboQuery.setItemText(5, _translate("MainWindow", "phone"))
        self.ButtonQuery.setText(_translate("MainWindow", "Go"))
        self.labelKeyWord.setText(_translate("MainWindow", "Key Word"))
        self.label.setText(_translate("MainWindow", "Sales Details"))
        self.menuNEW.setTitle(_translate("MainWindow", "NEW"))
        self.menuQUERY.setTitle(_translate("MainWindow", "QUERY"))
        self.actionNewRecord.setText(_translate("MainWindow", "New Record"))
        self.actionQuery.setText(_translate("MainWindow", "Query"))
        self.actionBy_Customer_ID.setText(_translate("MainWindow", "By Customer ID"))
        self.actionBy_Order_ID.setText(_translate("MainWindow", "By Order ID"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
