# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Business\SaleManagement\Sales-Management-PyQt5-MySQL\UI\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(854, 643)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabQuery = QtWidgets.QTabWidget(self.centralwidget)
        self.tabQuery.setStyleSheet("*{\n"
"    font-family: century gothic;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    font-family: Microsoft Yahei;\n"
"}\n"
"\n"
"QTextEdit{\n"
"    font-family: Microsoft Yahei;\n"
"}\n"
"\n"
"QComboBox{\n"
"    font-family: Microsoft Yahei;\n"
"}\n"
"\n"
"")
        self.tabQuery.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabQuery.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabQuery.setTabsClosable(False)
        self.tabQuery.setMovable(True)
        self.tabQuery.setTabBarAutoHide(False)
        self.tabQuery.setObjectName("tabQuery")
        self.tabNew = QtWidgets.QWidget()
        self.tabNew.setObjectName("tabNew")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabNew)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBoxCustomerInfo = QtWidgets.QGroupBox(self.tabNew)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(17)
        sizePolicy.setHeightForWidth(self.groupBoxCustomerInfo.sizePolicy().hasHeightForWidth())
        self.groupBoxCustomerInfo.setSizePolicy(sizePolicy)
        self.groupBoxCustomerInfo.setObjectName("groupBoxCustomerInfo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxCustomerInfo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 5, 10, 5)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelName = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.labelName.sizePolicy().hasHeightForWidth())
        self.labelName.setSizePolicy(sizePolicy)
        self.labelName.setMaximumSize(QtCore.QSize(16777215, 33))
        self.labelName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelName.setObjectName("labelName")
        self.horizontalLayout_2.addWidget(self.labelName)
        self.textName = QtWidgets.QLineEdit(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textName.sizePolicy().hasHeightForWidth())
        self.textName.setSizePolicy(sizePolicy)
        self.textName.setMaximumSize(QtCore.QSize(16777212, 33))
        self.textName.setStatusTip("")
        self.textName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textName.setStyleSheet("")
        self.textName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.textName.setObjectName("textName")
        self.horizontalLayout_2.addWidget(self.textName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 5, 10, 5)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelCustomerID = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.labelCustomerID.sizePolicy().hasHeightForWidth())
        self.labelCustomerID.setSizePolicy(sizePolicy)
        self.labelCustomerID.setMaximumSize(QtCore.QSize(16777215, 33))
        self.labelCustomerID.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCustomerID.setObjectName("labelCustomerID")
        self.horizontalLayout_3.addWidget(self.labelCustomerID)
        self.textCustomerID = QtWidgets.QLineEdit(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textCustomerID.sizePolicy().hasHeightForWidth())
        self.textCustomerID.setSizePolicy(sizePolicy)
        self.textCustomerID.setMaximumSize(QtCore.QSize(16777215, 33))
        self.textCustomerID.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textCustomerID.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.textCustomerID.setObjectName("textCustomerID")
        self.horizontalLayout_3.addWidget(self.textCustomerID)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, 5, 10, 5)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelProvince = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.labelProvince.sizePolicy().hasHeightForWidth())
        self.labelProvince.setSizePolicy(sizePolicy)
        self.labelProvince.setMaximumSize(QtCore.QSize(16777215, 33))
        self.labelProvince.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProvince.setObjectName("labelProvince")
        self.horizontalLayout_5.addWidget(self.labelProvince)
        self.comboProvince = QtWidgets.QComboBox(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboProvince.sizePolicy().hasHeightForWidth())
        self.comboProvince.setSizePolicy(sizePolicy)
        self.comboProvince.setMaximumSize(QtCore.QSize(16777215, 33))
        self.comboProvince.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboProvince.setObjectName("comboProvince")
        self.horizontalLayout_5.addWidget(self.comboProvince)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, 5, 10, 5)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelCity = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.labelCity.sizePolicy().hasHeightForWidth())
        self.labelCity.setSizePolicy(sizePolicy)
        self.labelCity.setMaximumSize(QtCore.QSize(16777215, 33))
        self.labelCity.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCity.setObjectName("labelCity")
        self.horizontalLayout_4.addWidget(self.labelCity)
        self.comboCity = QtWidgets.QComboBox(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboCity.sizePolicy().hasHeightForWidth())
        self.comboCity.setSizePolicy(sizePolicy)
        self.comboCity.setMaximumSize(QtCore.QSize(16777215, 33))
        self.comboCity.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboCity.setObjectName("comboCity")
        self.horizontalLayout_4.addWidget(self.comboCity)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setContentsMargins(0, 5, 10, 5)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelAddress = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.labelAddress.sizePolicy().hasHeightForWidth())
        self.labelAddress.setSizePolicy(sizePolicy)
        self.labelAddress.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAddress.setObjectName("labelAddress")
        self.horizontalLayout_6.addWidget(self.labelAddress)
        self.textAddress = QtWidgets.QTextEdit(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.textAddress.sizePolicy().hasHeightForWidth())
        self.textAddress.setSizePolicy(sizePolicy)
        self.textAddress.setMinimumSize(QtCore.QSize(0, 0))
        self.textAddress.setMaximumSize(QtCore.QSize(16777215, 120))
        self.textAddress.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textAddress.setObjectName("textAddress")
        self.horizontalLayout_6.addWidget(self.textAddress)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, 5, 10, 5)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelZip = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.labelZip.sizePolicy().hasHeightForWidth())
        self.labelZip.setSizePolicy(sizePolicy)
        self.labelZip.setMaximumSize(QtCore.QSize(16777215, 33))
        self.labelZip.setAlignment(QtCore.Qt.AlignCenter)
        self.labelZip.setObjectName("labelZip")
        self.horizontalLayout_7.addWidget(self.labelZip)
        self.textZip = QtWidgets.QLineEdit(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textZip.sizePolicy().hasHeightForWidth())
        self.textZip.setSizePolicy(sizePolicy)
        self.textZip.setMaximumSize(QtCore.QSize(16777215, 33))
        self.textZip.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textZip.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.textZip.setObjectName("textZip")
        self.horizontalLayout_7.addWidget(self.textZip)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(0, 5, 10, 5)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelPhone = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.labelPhone.sizePolicy().hasHeightForWidth())
        self.labelPhone.setSizePolicy(sizePolicy)
        self.labelPhone.setMaximumSize(QtCore.QSize(16777215, 33))
        self.labelPhone.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPhone.setObjectName("labelPhone")
        self.horizontalLayout_8.addWidget(self.labelPhone)
        self.textPhone = QtWidgets.QLineEdit(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textPhone.sizePolicy().hasHeightForWidth())
        self.textPhone.setSizePolicy(sizePolicy)
        self.textPhone.setMaximumSize(QtCore.QSize(16777215, 33))
        self.textPhone.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textPhone.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.textPhone.setObjectName("textPhone")
        self.horizontalLayout_8.addWidget(self.textPhone)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 5, 10, 5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.labelCustomerComment = QtWidgets.QLabel(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.labelCustomerComment.sizePolicy().hasHeightForWidth())
        self.labelCustomerComment.setSizePolicy(sizePolicy)
        self.labelCustomerComment.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCustomerComment.setObjectName("labelCustomerComment")
        self.horizontalLayout_13.addWidget(self.labelCustomerComment)
        self.textCustomerComment = QtWidgets.QTextEdit(self.groupBoxCustomerInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.textCustomerComment.sizePolicy().hasHeightForWidth())
        self.textCustomerComment.setSizePolicy(sizePolicy)
        self.textCustomerComment.setMaximumSize(QtCore.QSize(16777215, 120))
        self.textCustomerComment.setObjectName("textCustomerComment")
        self.horizontalLayout_13.addWidget(self.textCustomerComment)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.gridLayout_4.addWidget(self.groupBoxCustomerInfo, 0, 0, 1, 2)
        self.groupBoxOrderInfo = QtWidgets.QGroupBox(self.tabNew)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(17)
        sizePolicy.setHeightForWidth(self.groupBoxOrderInfo.sizePolicy().hasHeightForWidth())
        self.groupBoxOrderInfo.setSizePolicy(sizePolicy)
        self.groupBoxOrderInfo.setObjectName("groupBoxOrderInfo")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxOrderInfo)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 240, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 6, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 5, 0, 1, 1)
        self.buttonSubmit = QtWidgets.QPushButton(self.groupBoxOrderInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.buttonSubmit.sizePolicy().hasHeightForWidth())
        self.buttonSubmit.setSizePolicy(sizePolicy)
        self.buttonSubmit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.buttonSubmit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonSubmit.setCheckable(True)
        self.buttonSubmit.setChecked(False)
        self.buttonSubmit.setAutoDefault(False)
        self.buttonSubmit.setDefault(False)
        self.buttonSubmit.setFlat(False)
        self.buttonSubmit.setObjectName("buttonSubmit")
        self.gridLayout.addWidget(self.buttonSubmit, 5, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 5, 4, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(0, 5, 10, 5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelOrderDate = QtWidgets.QLabel(self.groupBoxOrderInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.labelOrderDate.sizePolicy().hasHeightForWidth())
        self.labelOrderDate.setSizePolicy(sizePolicy)
        self.labelOrderDate.setMaximumSize(QtCore.QSize(16777215, 33))
        self.labelOrderDate.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOrderDate.setObjectName("labelOrderDate")
        self.horizontalLayout_9.addWidget(self.labelOrderDate)
        self.dateOrder = QtWidgets.QDateEdit(self.groupBoxOrderInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dateOrder.sizePolicy().hasHeightForWidth())
        self.dateOrder.setSizePolicy(sizePolicy)
        self.dateOrder.setMaximumSize(QtCore.QSize(16777215, 33))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.dateOrder.setFont(font)
        self.dateOrder.setAutoFillBackground(False)
        self.dateOrder.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dateOrder.setReadOnly(False)
        self.dateOrder.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2030, 12, 30), QtCore.QTime(23, 59, 59)))
        self.dateOrder.setMaximumDate(QtCore.QDate(2030, 12, 30))
        self.dateOrder.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateOrder.setCalendarPopup(True)
        self.dateOrder.setDate(QtCore.QDate(2019, 7, 2))
        self.dateOrder.setObjectName("dateOrder")
        self.horizontalLayout_9.addWidget(self.dateOrder)
        self.gridLayout.addLayout(self.horizontalLayout_9, 0, 0, 1, 5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(0, 5, 10, 5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelItem = QtWidgets.QLabel(self.groupBoxOrderInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.labelItem.sizePolicy().hasHeightForWidth())
        self.labelItem.setSizePolicy(sizePolicy)
        self.labelItem.setMaximumSize(QtCore.QSize(16777215, 33))
        self.labelItem.setAlignment(QtCore.Qt.AlignCenter)
        self.labelItem.setObjectName("labelItem")
        self.horizontalLayout_10.addWidget(self.labelItem)
        self.comboItem = QtWidgets.QComboBox(self.groupBoxOrderInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboItem.sizePolicy().hasHeightForWidth())
        self.comboItem.setSizePolicy(sizePolicy)
        self.comboItem.setMaximumSize(QtCore.QSize(16777215, 33))
        self.comboItem.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboItem.setObjectName("comboItem")
        self.horizontalLayout_10.addWidget(self.comboItem)
        self.gridLayout.addLayout(self.horizontalLayout_10, 1, 0, 1, 5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(0, 5, 10, 5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labelQuantity = QtWidgets.QLabel(self.groupBoxOrderInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.labelQuantity.sizePolicy().hasHeightForWidth())
        self.labelQuantity.setSizePolicy(sizePolicy)
        self.labelQuantity.setMaximumSize(QtCore.QSize(16777215, 33))
        self.labelQuantity.setAlignment(QtCore.Qt.AlignCenter)
        self.labelQuantity.setObjectName("labelQuantity")
        self.horizontalLayout_11.addWidget(self.labelQuantity)
        self.comboQuantity = QtWidgets.QComboBox(self.groupBoxOrderInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboQuantity.sizePolicy().hasHeightForWidth())
        self.comboQuantity.setSizePolicy(sizePolicy)
        self.comboQuantity.setMaximumSize(QtCore.QSize(16777215, 33))
        self.comboQuantity.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboQuantity.setObjectName("comboQuantity")
        self.horizontalLayout_11.addWidget(self.comboQuantity)
        self.gridLayout.addLayout(self.horizontalLayout_11, 2, 0, 1, 5)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, 5, 10, 5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.labelOrderComment = QtWidgets.QLabel(self.groupBoxOrderInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.labelOrderComment.sizePolicy().hasHeightForWidth())
        self.labelOrderComment.setSizePolicy(sizePolicy)
        self.labelOrderComment.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOrderComment.setObjectName("labelOrderComment")
        self.horizontalLayout_14.addWidget(self.labelOrderComment)
        self.textOrderComment = QtWidgets.QTextEdit(self.groupBoxOrderInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.textOrderComment.sizePolicy().hasHeightForWidth())
        self.textOrderComment.setSizePolicy(sizePolicy)
        self.textOrderComment.setMaximumSize(QtCore.QSize(16777215, 120))
        self.textOrderComment.setObjectName("textOrderComment")
        self.horizontalLayout_14.addWidget(self.textOrderComment)
        self.gridLayout.addLayout(self.horizontalLayout_14, 3, 0, 1, 5)
        self.gridLayout_4.addWidget(self.groupBoxOrderInfo, 0, 2, 1, 2)
        self.tabQuery.addTab(self.tabNew, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setStyleSheet("font-size: 13px;\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboQuery = QtWidgets.QComboBox(self.groupBox_3)
        self.comboQuery.setObjectName("comboQuery")
        self.comboQuery.addItem("")
        self.comboQuery.addItem("")
        self.comboQuery.addItem("")
        self.comboQuery.addItem("")
        self.comboQuery.addItem("")
        self.comboQuery.addItem("")
        self.comboQuery.addItem("")
        self.horizontalLayout.addWidget(self.comboQuery)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.textKeyWord = QtWidgets.QLineEdit(self.groupBox_3)
        self.textKeyWord.setObjectName("textKeyWord")
        self.verticalLayout_2.addWidget(self.textKeyWord)
        self.buttonQuery = QtWidgets.QPushButton(self.groupBox_3)
        self.buttonQuery.setObjectName("buttonQuery")
        self.verticalLayout_2.addWidget(self.buttonQuery)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 2, 1, 1)
        self.textResult = QtWidgets.QTextEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textResult.sizePolicy().hasHeightForWidth())
        self.textResult.setSizePolicy(sizePolicy)
        self.textResult.setObjectName("textResult")
        self.gridLayout_2.addWidget(self.textResult, 0, 1, 1, 1)
        self.tabQuery.addTab(self.tab, "")
        self.gridLayout_3.addWidget(self.tabQuery, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 854, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("background-color: rgba(0, 0, 0, 75);\n"
"border-radius: 15px;")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabQuery.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBoxCustomerInfo.setTitle(_translate("MainWindow", "Customer Info"))
        self.labelName.setText(_translate("MainWindow", "Name"))
        self.textName.setPlaceholderText(_translate("MainWindow", "Name"))
        self.labelCustomerID.setText(_translate("MainWindow", "ID"))
        self.textCustomerID.setPlaceholderText(_translate("MainWindow", "ID"))
        self.labelProvince.setText(_translate("MainWindow", "Province"))
        self.labelCity.setText(_translate("MainWindow", "City"))
        self.labelAddress.setText(_translate("MainWindow", "Address"))
        self.textAddress.setPlaceholderText(_translate("MainWindow", "Address"))
        self.labelZip.setText(_translate("MainWindow", "Zip"))
        self.textZip.setPlaceholderText(_translate("MainWindow", "Zip"))
        self.labelPhone.setText(_translate("MainWindow", "Phone"))
        self.textPhone.setPlaceholderText(_translate("MainWindow", "Phone"))
        self.labelCustomerComment.setText(_translate("MainWindow", "Comment"))
        self.textCustomerComment.setPlaceholderText(_translate("MainWindow", "Customer Comment"))
        self.groupBoxOrderInfo.setTitle(_translate("MainWindow", "Order Info"))
        self.buttonSubmit.setText(_translate("MainWindow", "SUBMIT"))
        self.labelOrderDate.setText(_translate("MainWindow", "Date"))
        self.dateOrder.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.labelItem.setText(_translate("MainWindow", "Item"))
        self.labelQuantity.setText(_translate("MainWindow", "Quantity"))
        self.labelOrderComment.setText(_translate("MainWindow", "Comment"))
        self.textOrderComment.setPlaceholderText(_translate("MainWindow", "Order Comment"))
        self.tabQuery.setTabText(self.tabQuery.indexOf(self.tabNew), _translate("MainWindow", "New"))
        self.label.setText(_translate("MainWindow", "Key Word"))
        self.comboQuery.setItemText(0, _translate("MainWindow", "Name"))
        self.comboQuery.setItemText(1, _translate("MainWindow", "PersonID"))
        self.comboQuery.setItemText(2, _translate("MainWindow", "Province"))
        self.comboQuery.setItemText(3, _translate("MainWindow", "City"))
        self.comboQuery.setItemText(4, _translate("MainWindow", "Address"))
        self.comboQuery.setItemText(5, _translate("MainWindow", "Zip"))
        self.comboQuery.setItemText(6, _translate("MainWindow", "Phone"))
        self.buttonQuery.setText(_translate("MainWindow", "Go"))
        self.tabQuery.setTabText(self.tabQuery.indexOf(self.tab), _translate("MainWindow", "Page"))


